added sep argument in read_biom2phyloseq.R
microbiome/microbiome pull request #216
Opened 2023-07-25 15:31 UTC by plasde

This only applies for meta-data as separator is irrelevant for BIOM files. Default sep for read.csv is (of course) ",".

2023-07-25 21:09 UTC, antagomir commented
Check fails  - - did you document the change in the roxygen part, and run `devtools::document()` to update the manpages as well?

2023-07-25 21:09 UTC, antagomir requested changes

2023-07-25 21:09 UTC, antagomir commented on R/read_biom2phyloseq.R
> +                            taxonomy.file = NULL, metadata.file = NULL, sep = ",", ...)
this change should be also documented above in roxygen

2023-07-25 21:10 UTC, antagomir commented
You could update version number in DESCRIPTION file and mention the added thing in NEWS file. If you like, you are welcome to add yourself with "ctb" status in DESCRIPTION.

2023-07-27 09:48 UTC, plasde commented
Please ignore branch merge commit

2023-08-04 09:24 UTC, antagomir approved these changes
Thanks!

2023-08-04 09:24 UTC, merged